version: 0.2

env:
  variables:
    APP_ENV: 'prod'

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "📦 installing packages..."
      - npm install
  pre_build:
    commands:
      - echo "⚙️ Testing..."
      - echo "✅ Tests passed successfully."
  build:
    commands:
      - echo "🚧 Starting compiling packages..."
      - npm  run build
      - echo "✅ Build passed successfully."
  post_build:
    commands:
      - echo "🚚 Performing post-build packing and operations..."
      - echo "✅ Post build successful"

artifacts:
  base-directory: 'build*'
  discard-paths: yes
  files:
    - '**/*'  